echo "Use sh install.sh.bat to run on Linux"
npm install archiver
npm install mustache
npm install bcryptjs
npm install sqlite3
npm install @dqbd/tiktoken
npm install natural
npm install java
npm install undici
npm install htmlparser2
npm install novel-segment
npm install tinyld
npm install yaml
npm install papaparse
npm install gpt-tokenizer
npm install yaml
npm install wordcut
npm install nodemailer
npm install nodemailer-mailgun-transport
npm install line-by-line 
npm install fast-xml-parser 
npm install cron 
npm install ssh2 
npm install imapflow 
npm install marked
