# This script will init a Python environment with packages needed
# to run most of LLM generated Python code (aka code interpreter tool)
#
# If the environment exists (already initialized), then it will activate
# it and run the given Python code or commands within it.
# (C) 2024 TekMonks. All rights reserved.

#!/usr/bin/env bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PYTHON3=$( which python3 )

function init_python_env() {
  $PYTHON3 -m venv "$SCRIPT_DIR/neuranetpy"
  source "$SCRIPT_DIR/neuranetpy/bin/activate"
  pip install torch
  pip install opencv-python
  pip install scipy
  pip install SpeechRecognition
  pip install basemap-data
  pip install llvmlite
  pip install gensim
  pip install rasterio
  pip install imageio-ffmpeg
  pip install numpy
  pip install gradio
  pip install Fiona
  pip install plotly
  pip install scikit-image
  pip install PyMuPDF
  pip install dlib
  pip install pandas
  pip install scikit-learn
  pip install pycountry
  pip install python-pptx
  pip install Babel
  pip install nbclassic
  pip install statsmodels
  pip install jupyterlab
  pip install matplotlib
  pip install bokeh
  pip install mne
  pip install spacy
  pip install tables
  pip install pyproj
  pip install sympy
  pip install pdfminer.six
  pip install python-docx
  pip install cryptography
  pip install blis
  pip install lxml
  pip install PyWavelets
  pip install torchaudio
  pip install Pillow
  pip install h5py
  pip install resampy
  pip install fonttools
  pip install numba
  pip install Shapely
  pip install sentencepiece
  pip install torchtext
  pip install mtcnn
  pip install uvloop
  pip install networkx
  pip install pyphen
  pip install reportlab
  pip install pyzmq
  pip install xgboost
  pip install Theano-PyMC
  pip install debugpy
  pip install Faker
  pip install keras
  pip install arviz
  pip install pycryptodome
  pip install jedi
  pip install nltk
  pip install torchvision
  pip install jax
  pip install plotnine
  pip install Pygments
  pip install geopandas
  pip install xarray
  pip install cmudict
  pip install svglib
  pip install pymc3
  pip install thinc
  pip install basemap
  pip install future
  pip install ipython
  pip install pyswisseph
  pip install PyGObject
  pip install trimesh
  pip install textblob
  pip install dbus-python
  pip install countryinfo
  pip install mpmath
  pip install notebook
  pip install rdflib
  pip install aiohttp
  pip install pytz
  pip install srsly
  pip install bcrypt
  pip install shap
  pip install tornado
  pip install Brotli
  pip install watchfiles
  pip install moviepy
  pip install prompt-toolkit
  pip install audioread
  pip install jupyter-server
  pip install pydantic
  pip install PyNaCl
  pip install pytest
  pip install imageio
  pip install rpds-py
  pip install joblib
  pip install zopfli
  pip install regex
  pip install seaborn
  pip install nbconvert
  pip install odfpy
  pip install dnspython
  pip install weasyprint
  pip install librosa
  pip install openpyxl
  pip install python-dateutil
  pip install psutil
  pip install orjson
  pip install Werkzeug
  pip install httptools
  pip install patsy
  pip install PyPDF2
  pip install paramiko
  pip install tifffile
  pip install charset-normalizer
  pip install chardet
  pip install PyYAML
  pip install mutagen
  pip install exchange-calendars
  pip install extract-msg
  pip install IMAPClient
  pip install cffi
  pip install bleach
  pip install wordcloud
  pip install certifi
  pip install XlsxWriter
  pip install ipykernel
  pip install PyAudio
  pip install Wand
  pip install beautifulsoup4
  pip install Jinja2
  pip install ebcdic
  pip install absl-py
  pip install websockets
  pip install urllib3
  pip install kiwisolver
  pip install pygraphviz
  pip install geopy
  pip install pycparser
  pip install traitlets
  pip install EbookLib
  pip install olefile
  pip install html5lib
  pip install dill
  pip install preshed
  pip install jupyter-client
  pip install pyparsing
  pip install folium
  pip install parso
  pip install yarl
  pip install numexpr
  pip install py
  pip install click
  pip install Flask
  pip install xlrd
  pip install jupyter-core
  pip install kerykeion
  pip install jsonschema
  pip install anyio
  pip install text-unidecode
  pip install nbformat
  pip install tqdm
  pip install httpx
  pip install cairocffi
  pip install httpcore
  pip install mizani
  pip install nbclient
  pip install pdfrw
  pip install starlette
  pip install svgwrite
  pip install fastapi
  pip install opt-einsum
  pip install requests
  pip install idna
  pip install frozenlist
  pip install attrs
  pip install pooch
  pip install prometheus-client
  pip install loguru
  pip install pexpect
  pip install ujson
  pip install uvicorn
  pip install h11
  pip install hypercorn
  pip install h2
  pip install jupyterlab-server
  pip install websocket-client
  pip install smart-open
  pip install toolz
  pip install pyprover
  pip install python-apt
  pip install packaging
  pip install pathy
  pip install multidict
  pip install mistune
  pip install graphviz
  pip install pyshp
  pip install qrcode
  pip install pdfplumber
  pip install typer
  pip install python-multipart
  pip install h5netcdf
  pip install CairoSVG
  pip install einops
  pip install isodate
  pip install argcomplete
  pip install camelot-py
  pip install jsonpickle
  pip install geographiclib
  pip install pyttsx3
  pip install fpdf
  pip install markdown2
  pip install anytree
  pip install soupsieve
  pip install wrapt
  pip install backports.zoneinfo
  pip install tabulate
  pip install typing-extensions
  pip install hpack
  pip install pyzbar
  pip install pydub
  pip install cymem
  pip install email-validator
  pip install importlib-resources
  pip install matplotlib-venn
  pip install wcwidth
  pip install spacy-legacy
  pip install argon2-cffi-bindings
  pip install sortedcontainers
  pip install pyth3
  pip install gTTS
  pip install xarray-einstats
  pip install rarfile
  pip install wasabi
  pip install asttokens
  pip install nashpy
  pip install ipython-genutils
  pip install cloudpickle
  pip install defusedxml
  pip install referencing
  pip install pyluach
  pip install ffmpeg-python
  pip install pylog
  pip install branca
  pip install stack-data
  pip install tenacity
  pip install executing
  pip install wsproto
  pip install SoundFile
  pip install analytics-python
  pip install pyxlsb
  pip install fastjsonschema
  pip install textract
  pip install importlib-metadata
  pip install jupyterlab-pygments
  pip install pydot
  pip install tinycss2
  pip install tzlocal
  pip install pypandoc
  pip install python-dotenv
  pip install json5
  pip install murmurhash
  pip install fuzzywuzzy
  pip install Send2Trash
  pip install MarkupSafe
  pip install jsonschema-specifications
  pip install pluggy
  pip install pronouncing
  pip install catalogue
  pip install semver
  pip install Flask-Login
  pip install terminado
  pip install platformdirs
  pip install toml
  pip install markdownify
  pip install itsdangerous
  pip install affine
  pip install cssselect2
  pip install backoff
  pip install slicer
  pip install threadpoolctl
  pip install exceptiongroup
  pip install argon2-cffi
  pip install Flask-Cors
  pip install pytesseract
  pip install numpy-financial
  pip install ptyprocess
  pip install blinker
  pip install notebook-shim
  pip install tomli
  pip install fastprogress
  pip install hyperframe
  pip install pdfkit
  pip install requests-unixsocket
  pip install webencodings
  pip install pure-eval
  pip install pdf2image
  pip install backcall
  pip install six
  pip install filelock
  pip install imgkit
  pip install sniffio
  pip install munch
  pip install deprecat
  pip install tabula
  pip install matplotlib-inline
  pip install cachetools
  pip install xml-python
  pip install decorator
  pip install korean-lunar-calendar
  pip install priority
  pip install pandocfilters
  pip install monotonic
  pip install aiosignal
  pip install pydyf
  pip install click-plugins
  pip install cligj
  pip install pickleshare
  pip install zipp
  pip install comm
  pip install cycler
  pip install proglog
  pip install iniconfig
  pip install compressed-rtf
  pip install async-timeout
  pip install snuggs
  pip install entrypoints
  pip install nest-asyncio
  pip install ffmpy
  pip install pkgutil-resolve-name
  pip install et-xmlfile
  pip install distro-info
  pip install Flask-CacheBuster
  pip install docx2txt
  pip install gtts
  pip install sys
  pip install json
  pip install zlib
  pip install base64
  pip install os
  pip install tempfile
  pip install langdetect
  pip install openai-whisper
  pip install "numpy<2" 
}

if [ -d "$SCRIPT_DIR/neuranetpy" ]; then
  source "$SCRIPT_DIR/neuranetpy/bin/activate"
else
  init_python_env
fi

PYTHON3="$SCRIPT_DIR/neuranetpy/bin/python" # run the version of python inside the virtual environment
"$PYTHON3" "$@"
